GET http://localhost:3000/v1/products

###
GET http://localhost:3000/v1/products/e7dd559c-9951-4663-bb3e-f153c2f76a90


###
POST http://localhost:3000/v1/products
Accept: application/json
Content-Type: application/json

{
  "name": "iPhone 14 Plus",
  "type": "Product",
  "category_id": "920909ee-745b-4cc7-a62f-9abf005633c4",
  "barcode": "1234567890",
  "description": "Description of item goes here",
  "unitPrice": 8000,
  "amount": 8000
}

###
PATCH http://localhost:3000/v1/products/e7dd559c-9951-4663-bb3e-f153c2f76a90
Accept: application/json
Content-Type: application/json

{
  "name": "iPhone 14 Pro",
  "type": "Product",
  "category_id": "920909ee-745b-4cc7-a62f-9abf005633c4",
  "barcode": "1234567890",
  "description": "Description of item goes here",
  "unitPrice": 6000,
  "amount": 6000
}

###
DELETE http://localhost:3000/v1/products/e7dd559c-9951-4663-bb3e-f153c2f76a90
